<div class="portfolio-header">
    <div class="page-main">
        <div class="portfolio-container1">
            <div class="portfolio-col1  col-md-6 ">
                <div class="page-title-wrapper ">
                    <h1 class="page-title "><span class="base xhighlight" data-ui-id="page-title-wrapper">
                            <?php echo  $block->getLayout()->getBlock('page.main.title')->getPageTitle() ?></span></h1>
                    <p>Our Creative Design and Development Portfolio - Magento, Shopify, WooCommerce, Custom Web Apps showcase </p>
                </div>
            </div>
            <div class="portfolio-col2  col-md-6 ">
            </div>
        </div>
    </div>
</div>